// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataset.proto

package Protobuf;

public final class DatasetProtos {
  private DatasetProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    java.util.List<Protobuf.DatasetProtos.DataInstance> 
        getDataList();
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    Protobuf.DatasetProtos.DataInstance getData(int index);
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    java.util.List<? extends Protobuf.DatasetProtos.DataInstanceOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    Protobuf.DatasetProtos.DataInstanceOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DataSet}
   */
  public  static final class DataSet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataSet)
      DataSetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataSet.newBuilder() to construct.
    private DataSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataSet() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataSet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new java.util.ArrayList<Protobuf.DatasetProtos.DataInstance>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(Protobuf.DatasetProtos.DataInstance.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.DatasetProtos.internal_static_DataSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.DatasetProtos.internal_static_DataSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.DatasetProtos.DataSet.class, Protobuf.DatasetProtos.DataSet.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<Protobuf.DatasetProtos.DataInstance> data_;
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    public java.util.List<Protobuf.DatasetProtos.DataInstance> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    public java.util.List<? extends Protobuf.DatasetProtos.DataInstanceOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    public Protobuf.DatasetProtos.DataInstance getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .DataInstance data = 1;</code>
     */
    public Protobuf.DatasetProtos.DataInstanceOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protobuf.DatasetProtos.DataSet)) {
        return super.equals(obj);
      }
      Protobuf.DatasetProtos.DataSet other = (Protobuf.DatasetProtos.DataSet) obj;

      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protobuf.DatasetProtos.DataSet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protobuf.DatasetProtos.DataSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protobuf.DatasetProtos.DataSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protobuf.DatasetProtos.DataSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataSet)
        Protobuf.DatasetProtos.DataSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protobuf.DatasetProtos.internal_static_DataSet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protobuf.DatasetProtos.internal_static_DataSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protobuf.DatasetProtos.DataSet.class, Protobuf.DatasetProtos.DataSet.Builder.class);
      }

      // Construct using Protobuf.DatasetProtos.DataSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protobuf.DatasetProtos.internal_static_DataSet_descriptor;
      }

      @java.lang.Override
      public Protobuf.DatasetProtos.DataSet getDefaultInstanceForType() {
        return Protobuf.DatasetProtos.DataSet.getDefaultInstance();
      }

      @java.lang.Override
      public Protobuf.DatasetProtos.DataSet build() {
        Protobuf.DatasetProtos.DataSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Protobuf.DatasetProtos.DataSet buildPartial() {
        Protobuf.DatasetProtos.DataSet result = new Protobuf.DatasetProtos.DataSet(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protobuf.DatasetProtos.DataSet) {
          return mergeFrom((Protobuf.DatasetProtos.DataSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protobuf.DatasetProtos.DataSet other) {
        if (other == Protobuf.DatasetProtos.DataSet.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protobuf.DatasetProtos.DataSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protobuf.DatasetProtos.DataSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Protobuf.DatasetProtos.DataInstance> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new java.util.ArrayList<Protobuf.DatasetProtos.DataInstance>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protobuf.DatasetProtos.DataInstance, Protobuf.DatasetProtos.DataInstance.Builder, Protobuf.DatasetProtos.DataInstanceOrBuilder> dataBuilder_;

      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public java.util.List<Protobuf.DatasetProtos.DataInstance> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Protobuf.DatasetProtos.DataInstance getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder setData(
          int index, Protobuf.DatasetProtos.DataInstance value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder setData(
          int index, Protobuf.DatasetProtos.DataInstance.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder addData(Protobuf.DatasetProtos.DataInstance value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder addData(
          int index, Protobuf.DatasetProtos.DataInstance value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder addData(
          Protobuf.DatasetProtos.DataInstance.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder addData(
          int index, Protobuf.DatasetProtos.DataInstance.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends Protobuf.DatasetProtos.DataInstance> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Protobuf.DatasetProtos.DataInstance.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Protobuf.DatasetProtos.DataInstanceOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public java.util.List<? extends Protobuf.DatasetProtos.DataInstanceOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Protobuf.DatasetProtos.DataInstance.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            Protobuf.DatasetProtos.DataInstance.getDefaultInstance());
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public Protobuf.DatasetProtos.DataInstance.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, Protobuf.DatasetProtos.DataInstance.getDefaultInstance());
      }
      /**
       * <code>repeated .DataInstance data = 1;</code>
       */
      public java.util.List<Protobuf.DatasetProtos.DataInstance.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Protobuf.DatasetProtos.DataInstance, Protobuf.DatasetProtos.DataInstance.Builder, Protobuf.DatasetProtos.DataInstanceOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Protobuf.DatasetProtos.DataInstance, Protobuf.DatasetProtos.DataInstance.Builder, Protobuf.DatasetProtos.DataInstanceOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataSet)
    }

    // @@protoc_insertion_point(class_scope:DataSet)
    private static final Protobuf.DatasetProtos.DataSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protobuf.DatasetProtos.DataSet();
    }

    public static Protobuf.DatasetProtos.DataSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataSet>
        PARSER = new com.google.protobuf.AbstractParser<DataSet>() {
      @java.lang.Override
      public DataSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataSet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Protobuf.DatasetProtos.DataSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataInstanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataInstance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 state = 1;</code>
     * @return A list containing the state.
     */
    java.util.List<java.lang.Integer> getStateList();
    /**
     * <code>repeated int32 state = 1;</code>
     * @return The count of state.
     */
    int getStateCount();
    /**
     * <code>repeated int32 state = 1;</code>
     * @param index The index of the element to return.
     * @return The state at the given index.
     */
    int getState(int index);

    /**
     * <code>int32 value = 2;</code>
     * @return The value.
     */
    int getValue();

    /**
     * <code>repeated float policy = 3;</code>
     * @return A list containing the policy.
     */
    java.util.List<java.lang.Float> getPolicyList();
    /**
     * <code>repeated float policy = 3;</code>
     * @return The count of policy.
     */
    int getPolicyCount();
    /**
     * <code>repeated float policy = 3;</code>
     * @param index The index of the element to return.
     * @return The policy at the given index.
     */
    float getPolicy(int index);
  }
  /**
   * Protobuf type {@code DataInstance}
   */
  public  static final class DataInstance extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataInstance)
      DataInstanceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataInstance.newBuilder() to construct.
    private DataInstance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataInstance() {
      state_ = emptyIntList();
      policy_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataInstance();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataInstance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                state_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              state_.addInt(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                state_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                state_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {

              value_ = input.readInt32();
              break;
            }
            case 29: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                policy_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              policy_.addFloat(input.readFloat());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                policy_ = newFloatList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                policy_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          state_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          policy_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.DatasetProtos.internal_static_DataInstance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.DatasetProtos.internal_static_DataInstance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.DatasetProtos.DataInstance.class, Protobuf.DatasetProtos.DataInstance.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList state_;
    /**
     * <code>repeated int32 state = 1;</code>
     * @return A list containing the state.
     */
    public java.util.List<java.lang.Integer>
        getStateList() {
      return state_;
    }
    /**
     * <code>repeated int32 state = 1;</code>
     * @return The count of state.
     */
    public int getStateCount() {
      return state_.size();
    }
    /**
     * <code>repeated int32 state = 1;</code>
     * @param index The index of the element to return.
     * @return The state at the given index.
     */
    public int getState(int index) {
      return state_.getInt(index);
    }
    private int stateMemoizedSerializedSize = -1;

    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>int32 value = 2;</code>
     * @return The value.
     */
    public int getValue() {
      return value_;
    }

    public static final int POLICY_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.FloatList policy_;
    /**
     * <code>repeated float policy = 3;</code>
     * @return A list containing the policy.
     */
    public java.util.List<java.lang.Float>
        getPolicyList() {
      return policy_;
    }
    /**
     * <code>repeated float policy = 3;</code>
     * @return The count of policy.
     */
    public int getPolicyCount() {
      return policy_.size();
    }
    /**
     * <code>repeated float policy = 3;</code>
     * @param index The index of the element to return.
     * @return The policy at the given index.
     */
    public float getPolicy(int index) {
      return policy_.getFloat(index);
    }
    private int policyMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getStateList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(stateMemoizedSerializedSize);
      }
      for (int i = 0; i < state_.size(); i++) {
        output.writeInt32NoTag(state_.getInt(i));
      }
      if (value_ != 0) {
        output.writeInt32(2, value_);
      }
      if (getPolicyList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(policyMemoizedSerializedSize);
      }
      for (int i = 0; i < policy_.size(); i++) {
        output.writeFloatNoTag(policy_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < state_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(state_.getInt(i));
        }
        size += dataSize;
        if (!getStateList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        stateMemoizedSerializedSize = dataSize;
      }
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getPolicyList().size();
        size += dataSize;
        if (!getPolicyList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        policyMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protobuf.DatasetProtos.DataInstance)) {
        return super.equals(obj);
      }
      Protobuf.DatasetProtos.DataInstance other = (Protobuf.DatasetProtos.DataInstance) obj;

      if (!getStateList()
          .equals(other.getStateList())) return false;
      if (getValue()
          != other.getValue()) return false;
      if (!getPolicyList()
          .equals(other.getPolicyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStateCount() > 0) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getStateList().hashCode();
      }
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      if (getPolicyCount() > 0) {
        hash = (37 * hash) + POLICY_FIELD_NUMBER;
        hash = (53 * hash) + getPolicyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protobuf.DatasetProtos.DataInstance parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataInstance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protobuf.DatasetProtos.DataInstance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protobuf.DatasetProtos.DataInstance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protobuf.DatasetProtos.DataInstance prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataInstance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataInstance)
        Protobuf.DatasetProtos.DataInstanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protobuf.DatasetProtos.internal_static_DataInstance_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protobuf.DatasetProtos.internal_static_DataInstance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protobuf.DatasetProtos.DataInstance.class, Protobuf.DatasetProtos.DataInstance.Builder.class);
      }

      // Construct using Protobuf.DatasetProtos.DataInstance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;

        policy_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protobuf.DatasetProtos.internal_static_DataInstance_descriptor;
      }

      @java.lang.Override
      public Protobuf.DatasetProtos.DataInstance getDefaultInstanceForType() {
        return Protobuf.DatasetProtos.DataInstance.getDefaultInstance();
      }

      @java.lang.Override
      public Protobuf.DatasetProtos.DataInstance build() {
        Protobuf.DatasetProtos.DataInstance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Protobuf.DatasetProtos.DataInstance buildPartial() {
        Protobuf.DatasetProtos.DataInstance result = new Protobuf.DatasetProtos.DataInstance(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          state_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.state_ = state_;
        result.value_ = value_;
        if (((bitField0_ & 0x00000002) != 0)) {
          policy_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.policy_ = policy_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protobuf.DatasetProtos.DataInstance) {
          return mergeFrom((Protobuf.DatasetProtos.DataInstance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protobuf.DatasetProtos.DataInstance other) {
        if (other == Protobuf.DatasetProtos.DataInstance.getDefaultInstance()) return this;
        if (!other.state_.isEmpty()) {
          if (state_.isEmpty()) {
            state_ = other.state_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStateIsMutable();
            state_.addAll(other.state_);
          }
          onChanged();
        }
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        if (!other.policy_.isEmpty()) {
          if (policy_.isEmpty()) {
            policy_ = other.policy_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePolicyIsMutable();
            policy_.addAll(other.policy_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protobuf.DatasetProtos.DataInstance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protobuf.DatasetProtos.DataInstance) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList state_ = emptyIntList();
      private void ensureStateIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          state_ = mutableCopy(state_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 state = 1;</code>
       * @return A list containing the state.
       */
      public java.util.List<java.lang.Integer>
          getStateList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(state_) : state_;
      }
      /**
       * <code>repeated int32 state = 1;</code>
       * @return The count of state.
       */
      public int getStateCount() {
        return state_.size();
      }
      /**
       * <code>repeated int32 state = 1;</code>
       * @param index The index of the element to return.
       * @return The state at the given index.
       */
      public int getState(int index) {
        return state_.getInt(index);
      }
      /**
       * <code>repeated int32 state = 1;</code>
       * @param index The index to set the value at.
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(
          int index, int value) {
        ensureStateIsMutable();
        state_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 state = 1;</code>
       * @param value The state to add.
       * @return This builder for chaining.
       */
      public Builder addState(int value) {
        ensureStateIsMutable();
        state_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 state = 1;</code>
       * @param values The state to add.
       * @return This builder for chaining.
       */
      public Builder addAllState(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureStateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, state_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 state = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        state_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>int32 value = 2;</code>
       * @return The value.
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>int32 value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList policy_ = emptyFloatList();
      private void ensurePolicyIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          policy_ = mutableCopy(policy_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float policy = 3;</code>
       * @return A list containing the policy.
       */
      public java.util.List<java.lang.Float>
          getPolicyList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(policy_) : policy_;
      }
      /**
       * <code>repeated float policy = 3;</code>
       * @return The count of policy.
       */
      public int getPolicyCount() {
        return policy_.size();
      }
      /**
       * <code>repeated float policy = 3;</code>
       * @param index The index of the element to return.
       * @return The policy at the given index.
       */
      public float getPolicy(int index) {
        return policy_.getFloat(index);
      }
      /**
       * <code>repeated float policy = 3;</code>
       * @param index The index to set the value at.
       * @param value The policy to set.
       * @return This builder for chaining.
       */
      public Builder setPolicy(
          int index, float value) {
        ensurePolicyIsMutable();
        policy_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float policy = 3;</code>
       * @param value The policy to add.
       * @return This builder for chaining.
       */
      public Builder addPolicy(float value) {
        ensurePolicyIsMutable();
        policy_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float policy = 3;</code>
       * @param values The policy to add.
       * @return This builder for chaining.
       */
      public Builder addAllPolicy(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensurePolicyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, policy_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float policy = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPolicy() {
        policy_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataInstance)
    }

    // @@protoc_insertion_point(class_scope:DataInstance)
    private static final Protobuf.DatasetProtos.DataInstance DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protobuf.DatasetProtos.DataInstance();
    }

    public static Protobuf.DatasetProtos.DataInstance getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataInstance>
        PARSER = new com.google.protobuf.AbstractParser<DataInstance>() {
      @java.lang.Override
      public DataInstance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataInstance(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataInstance> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataInstance> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Protobuf.DatasetProtos.DataInstance getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataSet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataInstance_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataInstance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rdataset.proto\"&\n\007DataSet\022\033\n\004data\030\001 \003(\013" +
      "2\r.DataInstance\"<\n\014DataInstance\022\r\n\005state" +
      "\030\001 \003(\005\022\r\n\005value\030\002 \001(\005\022\016\n\006policy\030\003 \003(\002B\031\n" +
      "\010ProtobufB\rDatasetProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DataSet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataSet_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_DataInstance_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataInstance_descriptor,
        new java.lang.String[] { "State", "Value", "Policy", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
